### PR TITLE
closes 17 add demo for transductive evaluator

### LINKED ISSUE #17: Add demo for Transductive Evaluator

### PR DESCRIPTION
**Pull request by Tremirre**
Added short preview of how TE works and how it can be used.

Let me know if anything is missing or should be changed

### CODE REVIEW

**Review by azywot — APPROVED** [review]
Nice and clear, GJ 😊😎
One, optional thing - maybe it would be nice to compare logistic regression with some other model as in the notebook it's already stated about the _model's capacity [...]_

**Comment by Tremirre** [comment]
> Nice and clear, GJ 😊😎 One, optional thing - maybe it would be nice to compare logistic regression with some other model as in the notebook it's already stated about the _model's capacity [...]_

Tbh for this particular dataset the choice of won't help as much cause the classes have severe overlap (which was intentional - it allowed to more easily showcase how reliability change). I might change the phrasing so that it's more clear that it depends on the model's capacity AND the dataset itself.

I added SVN but the results are roughly the same:
image

**Comment by Tremirre** [comment]
Although for KNN it looks much more interesting (due to overlap KNN is performs very poorly)
image

I can leave these two as a part of the notebook

**Comment by azywot** [comment]
Thanks for the clarification and adding a new model 👍I think now it's ready to go 🚀

**Review by zuzg — APPROVED** [review]

**Pull request merged**
